name: Build and Dockerize

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
    # install gradle 4.8.1
      - name: Install Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-4.8.1-bin.zip
          sudo mkdir /opt/gradle
          sudo unzip -d /opt/gradle gradle-4.8.1-bin.zip
          export PATH=$PATH:/opt/gradle/gradle-4.8.1/bin
          gradle -v
          
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Run Build Script
        run: |
          chmod +x ./build.sh
          ./build.sh
          
      # - name: Publish Docker Image
      #   run: |
      #     echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      #     docker push ${org}/${name}:${version}-bronze
